# Generated by Django 4.2.7 on 2023-11-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_system', models.CharField(max_length=200, verbose_name='Тип ОС:')),
                ('version', models.CharField(max_length=200, verbose_name='Версия ОС:')),
                ('architecture', models.CharField(max_length=200, verbose_name='Архитектура:')),
                ('log_history', models.CharField(max_length=200, verbose_name='История логов:'))
            ],
        ),
    ]
